# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48fdeebd48a56566b3fa95e34a66a82f28f8fe9bad4e0d2e1bcad5e6f33948b9095e8ab755e152a67b75032c1024cbcc3bbf25a31912b035fdf4d2553c9d520d

test:
  secret_key_base: 667573df3a23bdc2c32332e7e9a58d2cd2d0351836177db350150a95c09205a19bfda9efd9e28c8c05735e834b01054be30c134e86a916da5a59e9d3e4ab2f3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
